eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  data:
    cassandra:
      keyspace-name: pinterest
      contact-points: localhost
      port: 9042
      schema-action: create-if-not-exists
